"""risk scenario context

Revision ID: 09890c3538d8
Revises: 6de9241b817d
Create Date: 2025-08-05 12:38:22.204597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09890c3538d8'
down_revision: Union[str, Sequence[str], None] = '6de9241b817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('risk_scenarios_asset_group_id_fkey'), 'risk_scenarios', type_='foreignkey')
    op.drop_constraint(op.f('risk_scenarios_asset_type_id_fkey'), 'risk_scenarios', type_='foreignkey')
    op.drop_constraint(op.f('risk_scenarios_asset_id_fkey'), 'risk_scenarios', type_='foreignkey')
    op.drop_column('risk_scenarios', 'lifecycle_states')
    op.drop_column('risk_scenarios', 'likelihood')
    op.drop_column('risk_scenarios', 'asset_id')
    op.drop_column('risk_scenarios', 'asset_group_id')
    op.drop_column('risk_scenarios', 'asset_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('asset_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('risk_scenarios', sa.Column('asset_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('risk_scenarios', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('risk_scenarios', sa.Column('likelihood', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('risk_scenarios', sa.Column('lifecycle_states', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('risk_scenarios_asset_id_fkey'), 'risk_scenarios', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('risk_scenarios_asset_type_id_fkey'), 'risk_scenarios', 'asset_types', ['asset_type_id'], ['id'])
    op.create_foreign_key(op.f('risk_scenarios_asset_group_id_fkey'), 'risk_scenarios', 'asset_groups', ['asset_group_id'], ['id'])
    # ### end Alembic commands ###
