"""requirement owner

Revision ID: 136674945f1f
Revises: d02775ec4f55
Create Date: 2025-09-01 17:44:42.215643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136674945f1f'
down_revision: Union[str, Sequence[str], None] = 'd02775ec4f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_requirement_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_requirement_id'], ['framework_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_requirement_id', 'scope_type', 'scope_id', 'user_id', 'role', name='uq_requirement_owner')
    )
    op.create_index('ix_requirement_owner_scope', 'requirement_owners', ['scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_requirement_owners_framework_requirement_id'), 'requirement_owners', ['framework_requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_owners_id'), 'requirement_owners', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_owners_user_id'), 'requirement_owners', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_owners_user_id'), table_name='requirement_owners')
    op.drop_index(op.f('ix_requirement_owners_id'), table_name='requirement_owners')
    op.drop_index(op.f('ix_requirement_owners_framework_requirement_id'), table_name='requirement_owners')
    op.drop_index('ix_requirement_owner_scope', table_name='requirement_owners')
    op.drop_table('requirement_owners')
    # ### end Alembic commands ###
