"""update risk_scenario fix asset_type

Revision ID: 21897d63c0d9
Revises: f9e9f4177e1b
Create Date: 2025-07-31 13:39:24.788574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21897d63c0d9'
down_revision: Union[str, Sequence[str], None] = 'f9e9f4177e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'risk_scenarios', 'asset_types', ['asset_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_scenarios', type_='foreignkey')
    op.drop_column('risk_scenarios', 'asset_type_id')
    # ### end Alembic commands ###
