"""use mixin

Revision ID: 238676841111
Revises: 21fb752753e1
Create Date: 2025-07-24 11:14:41.245112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238676841111'
down_revision: Union[str, Sequence[str], None] = '21fb752753e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_groups', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.alter_column('asset_groups', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_lifecycle_events', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_lifecycle_events', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_lifecycle_events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_maintenance', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_maintenance', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_maintenance', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_owners', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_owners', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_owners', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_relations', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_relations', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_relations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_scans', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_scans', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_scans', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_security_profiles', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('asset_security_profiles', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('asset_security_profiles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('asset_tags', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.alter_column('asset_tags', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('asset_tags', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint(op.f('asset_tags_name_key'), 'asset_tags', type_='unique')
    op.alter_column('asset_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('asset_types', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint(op.f('asset_types_name_key'), 'asset_types', type_='unique')
    op.drop_column('asset_types', 'create_at')
    op.add_column('assets', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.alter_column('assets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('vulnerability_threat_links', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability_threat_links', 'enabled')
    op.alter_column('assets', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('assets', 'enabled')
    op.add_column('asset_types', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('asset_types_name_key'), 'asset_types', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset_types', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('asset_types', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_unique_constraint(op.f('asset_tags_name_key'), 'asset_tags', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset_tags', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('asset_tags', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('asset_tags', 'enabled')
    op.alter_column('asset_security_profiles', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_security_profiles', 'name')
    op.drop_column('asset_security_profiles', 'enabled')
    op.alter_column('asset_scans', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_scans', 'name')
    op.drop_column('asset_scans', 'enabled')
    op.alter_column('asset_relations', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_relations', 'name')
    op.drop_column('asset_relations', 'enabled')
    op.alter_column('asset_owners', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_owners', 'name')
    op.drop_column('asset_owners', 'enabled')
    op.alter_column('asset_maintenance', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_maintenance', 'name')
    op.drop_column('asset_maintenance', 'enabled')
    op.alter_column('asset_lifecycle_events', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_lifecycle_events', 'name')
    op.drop_column('asset_lifecycle_events', 'enabled')
    op.alter_column('asset_groups', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('asset_groups', 'enabled')
    # ### end Alembic commands ###
