"""risk scenario context-refactor

Revision ID: 23e2abd7c6b9
Revises: 09890c3538d8
Create Date: 2025-08-05 13:54:17.032670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23e2abd7c6b9'
down_revision: Union[str, Sequence[str], None] = '09890c3538d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scenario_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_scenario_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_group_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_states', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_tag_id'], ['asset_tags.id'], ),
    sa.ForeignKeyConstraint(['risk_scenario_id'], ['risk_scenarios.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_context_impact_ratings',
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['impact_domains.id'], ),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('impact_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_ratings',
    sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['impact_domains.id'], name=op.f('impact_ratings_domain_id_fkey')),
    sa.ForeignKeyConstraint(['scenario_id'], ['risk_scenarios.id'], name=op.f('impact_ratings_scenario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('impact_ratings_pkey'))
    )
    op.drop_table('risk_context_impact_ratings')
    op.drop_table('risk_scenario_contexts')
    # ### end Alembic commands ###
