"""update controls to multilang

Revision ID: 245576892309
Revises: 7fa211336acc
Create Date: 2025-07-29 17:52:16.377152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '245576892309'
down_revision: Union[str, Sequence[str], None] = '7fa211336acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('reference_code', sa.String(), nullable=True))
    op.add_column('controls', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('controls', sa.Column('title_de', sa.String(), nullable=True))
    op.add_column('controls', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('description_de', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('control_type', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('controls', sa.Column('control_concept', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('controls', sa.Column('properties', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('controls', sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('controls', sa.Column('security_domains', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'controls', ['reference_code'])
    op.drop_column('controls', 'name')
    op.drop_column('controls', 'type')
    op.drop_column('controls', 'description')
    op.drop_column('controls', 'status')
    op.drop_column('controls', 'updated_at')
    op.drop_column('controls', 'standard_refs')
    op.drop_column('controls', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('standard_refs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('status', postgresql.ENUM('proposed', 'in_progress', 'implemented', 'verified', name='controlstatus'), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('type', postgresql.ENUM('preventive', 'detective', 'corrective', 'deterrent', 'compensating', 'recovery', 'directive', name='controltype'), autoincrement=False, nullable=False))
    op.add_column('controls', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'controls', type_='unique')
    op.drop_column('controls', 'security_domains')
    op.drop_column('controls', 'capabilities')
    op.drop_column('controls', 'properties')
    op.drop_column('controls', 'control_concept')
    op.drop_column('controls', 'control_type')
    op.drop_column('controls', 'description_de')
    op.drop_column('controls', 'description_en')
    op.drop_column('controls', 'title_de')
    op.drop_column('controls', 'title_en')
    op.drop_column('controls', 'reference_code')
    # ### end Alembic commands ###
