"""add prefill contexts

Revision ID: 247a1dfcc239
Revises: 8a42653d0925
Create Date: 2025-08-26 14:38:28.985008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247a1dfcc239'
down_revision: Union[str, Sequence[str], None] = '8a42653d0925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_rsc_scope_pair', 'risk_scenario_contexts', ['scope_type', 'scope_id'], unique=False)
    op.create_unique_constraint('uq_rsc_scenario_scope', 'risk_scenario_contexts', ['risk_scenario_id', 'scope_type', 'scope_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rsc_scenario_scope', 'risk_scenario_contexts', type_='unique')
    op.drop_index('ix_rsc_scope_pair', table_name='risk_scenario_contexts')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
