"""risk add risk scores3

Revision ID: 2808d3d16cc1
Revises: aabc9b1f8ff1
Create Date: 2025-08-06 22:52:55.266365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2808d3d16cc1'
down_revision: Union[str, Sequence[str], None] = 'aabc9b1f8ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
