"""enable framework version

Revision ID: 3744aec7b7aa
Revises: 6d78eb751ac8
Create Date: 2025-09-04 16:06:22.122409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3744aec7b7aa'
down_revision: Union[str, Sequence[str], None] = '6d78eb751ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_versions', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_versions', 'enabled')
    # ### end Alembic commands ###
