"""add risk-scenario enrich

Revision ID: 37bd92ae4bdd
Revises: b643b3bf70ca
Create Date: 2025-08-03 17:38:31.071603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bd92ae4bdd'
down_revision: Union[str, Sequence[str], None] = 'b643b3bf70ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
