"""update Threats2

Revision ID: 380f0ac8d7c6
Revises: c6bafaff55a5
Create Date: 2025-07-23 17:12:09.212911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380f0ac8d7c6'
down_revision: Union[str, Sequence[str], None] = 'c6bafaff55a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('risk_source', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threats', schema='secura')
    # ### end Alembic commands ###
