"""update assets with details and location

Revision ID: 395de38989b6
Revises: 4172805a37ee
Create Date: 2025-07-30 15:13:48.222290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395de38989b6'
down_revision: Union[str, Sequence[str], None] = '4172805a37ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('location', sa.String(length=1000), nullable=True))
    op.add_column('assets', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'details')
    op.drop_column('assets', 'location')
    # ### end Alembic commands ###
