"""asset_type link control-threat-vuln

Revision ID: 3dfc674bcfe6
Revises: 2808d3d16cc1
Create Date: 2025-08-07 14:07:34.146492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfc674bcfe6'
down_revision: Union[str, Sequence[str], None] = '2808d3d16cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type_threat_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'threat_id', name='_asset_type_threat_uc')
    )
    op.create_index(op.f('ix_asset_type_threat_links_id'), 'asset_type_threat_links', ['id'], unique=False)
    op.create_table('asset_type_vulnerability_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'vulnerability_id', name='_asset_type_vuln_uc')
    )
    op.create_index(op.f('ix_asset_type_vulnerability_links_id'), 'asset_type_vulnerability_links', ['id'], unique=False)
    op.create_table('asset_type_control_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'control_id', name='_asset_type_control_uc')
    )
    op.create_index(op.f('ix_asset_type_control_links_id'), 'asset_type_control_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_type_control_links_id'), table_name='asset_type_control_links')
    op.drop_table('asset_type_control_links')
    op.drop_index(op.f('ix_asset_type_vulnerability_links_id'), table_name='asset_type_vulnerability_links')
    op.drop_table('asset_type_vulnerability_links')
    op.drop_index(op.f('ix_asset_type_threat_links_id'), table_name='asset_type_threat_links')
    op.drop_table('asset_type_threat_links')
    # ### end Alembic commands ###
