"""update risk_scenarios

Revision ID: 4172805a37ee
Revises: eaccd1ba8bcc
Create Date: 2025-07-30 10:01:50.935955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4172805a37ee'
down_revision: Union[str, Sequence[str], None] = 'eaccd1ba8bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('title_en', sa.String(length=255), nullable=False))
    op.add_column('risk_scenarios', sa.Column('title_de', sa.String(length=255), nullable=False))
    op.add_column('risk_scenarios', sa.Column('description_en', sa.String(length=1000), nullable=True))
    op.add_column('risk_scenarios', sa.Column('description_de', sa.String(length=1000), nullable=True))
    op.drop_column('risk_scenarios', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('risk_scenarios', 'description_de')
    op.drop_column('risk_scenarios', 'description_en')
    op.drop_column('risk_scenarios', 'title_de')
    op.drop_column('risk_scenarios', 'title_en')
    # ### end Alembic commands ###
