"""update risk_scenario with tags and group

Revision ID: 4ae9d59b4621
Revises: 395de38989b6
Create Date: 2025-07-31 13:05:19.606557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae9d59b4621'
down_revision: Union[str, Sequence[str], None] = '395de38989b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scenario_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_de', sa.String(length=200), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('description_de', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scenario_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_de', sa.String(length=200), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('description_de', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['risk_scenario_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scenario_tags',
    sa.Column('risk_scenario_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_scenario_id'], ['risk_scenarios.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['asset_tags.id'], ),
    sa.PrimaryKeyConstraint('risk_scenario_id', 'tag_id')
    )
    op.add_column('risk_scenarios', sa.Column('asset_group_id', sa.Integer(), nullable=True))
    op.add_column('risk_scenarios', sa.Column('lifecycle_states', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('risk_scenarios', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'risk_scenarios', 'risk_scenario_subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'risk_scenarios', 'asset_groups', ['asset_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_scenarios', type_='foreignkey')
    op.drop_constraint(None, 'risk_scenarios', type_='foreignkey')
    op.drop_column('risk_scenarios', 'subcategory_id')
    op.drop_column('risk_scenarios', 'lifecycle_states')
    op.drop_column('risk_scenarios', 'asset_group_id')
    op.drop_table('risk_scenario_tags')
    op.drop_table('risk_scenario_subcategories')
    op.drop_table('risk_scenario_categories')
    # ### end Alembic commands ###
