"""risk scenario context-refactor 2

Revision ID: 4e31a05c6fd1
Revises: 23e2abd7c6b9
Create Date: 2025-08-05 14:11:32.060857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e31a05c6fd1'
down_revision: Union[str, Sequence[str], None] = '23e2abd7c6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
