"""add category to control

Revision ID: 511b103757be
Revises: f40c0cba9ebd
Create Date: 2025-08-01 20:13:24.881919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511b103757be'
down_revision: Union[str, Sequence[str], None] = 'f40c0cba9ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'category')
    # ### end Alembic commands ###
