"""update asset_tag category

Revision ID: 53263355cdd1
Revises: 21897d63c0d9
Create Date: 2025-07-31 17:29:14.132341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53263355cdd1'
down_revision: Union[str, Sequence[str], None] = '21897d63c0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_tags', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_tags', 'category')
    # ### end Alembic commands ###
