"""control_context_link2

Revision ID: 5432d828ba71
Revises: bffb29b4f3ea
Create Date: 2025-08-11 11:20:24.725642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5432d828ba71'
down_revision: Union[str, Sequence[str], None] = 'bffb29b4f3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_context_effect_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('score_override', sa.Float(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['impact_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_scenario_context_id', 'control_id', 'domain_id', name='uq_ctx_override')
    )
    op.create_table('control_context_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('evidence_note', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_scenario_context_id', 'control_id', name='uq_ctrl_ctx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_context_links')
    op.drop_table('control_context_effect_overrides')
    # ### end Alembic commands ###
