"""asset_type threats score - justify

Revision ID: 5a48b674e6cb
Revises: 3dfc674bcfe6
Create Date: 2025-08-07 18:07:40.989331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a48b674e6cb'
down_revision: Union[str, Sequence[str], None] = '3dfc674bcfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type_threat_links', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('asset_type_threat_links', sa.Column('justification', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_type_threat_links', 'justification')
    op.drop_column('asset_type_threat_links', 'score')
    # ### end Alembic commands ###
