"""add policy layer4

Revision ID: 5f2a41cfbe34
Revises: 4c0ef3fd81e2
Create Date: 2025-08-13 12:43:50.672593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2a41cfbe34'
down_revision: Union[str, Sequence[str], None] = '4c0ef3fd81e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_appetite_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag_id', sa.Integer(), nullable=True),
    sa.Column('asset_group_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=1), nullable=True),
    sa.Column('green_max', sa.Integer(), nullable=False),
    sa.Column('amber_max', sa.Integer(), nullable=False),
    sa.Column('domain_caps_json', sa.JSON(), nullable=True),
    sa.Column('sla_days_amber', sa.Integer(), nullable=True),
    sa.Column('sla_days_red', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ),
    sa.ForeignKeyConstraint(['asset_tag_id'], ['asset_tags.id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_appetite_policies')
    # ### end Alembic commands ###
