"""add status and .. to control-risk-link

Revision ID: 6765ce3762de
Revises: b1895b0bf4c3
Create Date: 2025-08-01 19:10:58.302782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6765ce3762de'
down_revision: Union[str, Sequence[str], None] = 'b1895b0bf4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_risk_links', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('control_risk_links', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('control_risk_links', sa.Column('residual_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_risk_links', 'residual_score')
    op.drop_column('control_risk_links', 'justification')
    op.drop_column('control_risk_links', 'status')
    # ### end Alembic commands ###
