"""edit persons

Revision ID: 688f577bc07a
Revises: b894fa6eeec5
Create Date: 2025-08-26 09:42:20.842285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688f577bc07a'
down_revision: Union[str, Sequence[str], None] = 'b894fa6eeec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('display_name', sa.String(length=200), nullable=True))
    op.add_column('persons', sa.Column('initials', sa.String(length=8), nullable=True))
    op.add_column('persons', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('persons', sa.Column('kind', sa.String(length=16), nullable=True))
    op.add_column('persons', sa.Column('external_ids', sa.JSON(), nullable=True))
    op.add_column('persons', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'timezone')
    op.drop_column('persons', 'external_ids')
    op.drop_column('persons', 'kind')
    op.drop_column('persons', 'avatar_url')
    op.drop_column('persons', 'initials')
    op.drop_column('persons', 'display_name')
    # ### end Alembic commands ###
