"""Initial Full Assets

Revision ID: 6a9d9bc9e7e3
Revises: d6ffb1675473
Create Date: 2025-07-18 09:49:51.978027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9d9bc9e7e3'
down_revision: Union[str, Sequence[str], None] = 'd6ffb1675473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['secura.asset_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='secura'
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['secura.asset_groups.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['secura.asset_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='secura'
    )
    op.create_table('asset_lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('related_asset_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scanner', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('vulns_found', sa.Integer(), nullable=True),
    sa.Column('report_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.create_table('asset_security_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('confidentiality', sa.Integer(), nullable=True),
    sa.Column('integrity', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['secura.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id'),
    schema='secura'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_security_profiles', schema='secura')
    op.drop_table('asset_scans', schema='secura')
    op.drop_table('asset_relations', schema='secura')
    op.drop_table('asset_owners', schema='secura')
    op.drop_table('asset_maintenance', schema='secura')
    op.drop_table('asset_lifecycle_events', schema='secura')
    op.drop_table('assets', schema='secura')
    op.drop_table('asset_types', schema='secura')
    op.drop_table('asset_groups', schema='secura')
    # ### end Alembic commands ###
