"""add effect_type to control_risk_link

Revision ID: 6bc555158161
Revises: 511b103757be
Create Date: 2025-08-02 09:35:32.320353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc555158161'
down_revision: Union[str, Sequence[str], None] = '511b103757be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_risk_links', sa.Column('effect_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_risk_links', 'effect_type')
    # ### end Alembic commands ###
