"""add person to users

Revision ID: 6d78eb751ac8
Revises: cc7315a5f79c
Create Date: 2025-09-03 09:22:57.155906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d78eb751ac8'
down_revision: Union[str, Sequence[str], None] = 'cc7315a5f79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iam_users', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_iam_users_email'), table_name='iam_users')
    op.create_index(op.f('ix_iam_users_email'), 'iam_users', ['email'], unique=True)
    op.create_foreign_key(None, 'iam_users', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iam_users', type_='foreignkey')
    op.drop_index(op.f('ix_iam_users_email'), table_name='iam_users')
    op.create_index(op.f('ix_iam_users_email'), 'iam_users', ['email'], unique=False)
    op.drop_column('iam_users', 'person_id')
    # ### end Alembic commands ###
