"""add unique contraint control_effect_rating

Revision ID: 6de9241b817d
Revises: 37bd92ae4bdd
Create Date: 2025-08-05 10:31:22.609290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de9241b817d'
down_revision: Union[str, Sequence[str], None] = '37bd92ae4bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_control_effect_rating_unique', 'control_effect_rating', ['risk_scenario_id', 'control_id', 'domain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_control_effect_rating_unique', 'control_effect_rating', type_='unique')
    # ### end Alembic commands ###
