"""scope migration to assets

Revision ID: 6fc58a7cf947
Revises: 84fb1d52b75c
Create Date: 2025-08-16 15:46:23.142432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc58a7cf947'
down_revision: Union[str, Sequence[str], None] = '84fb1d52b75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('business_unit_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'org_sites', ['site_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assets', 'org_business_units', ['business_unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assets', 'org_entities', ['entity_id'], ['id'], ondelete='SET NULL')
    op.alter_column('risk_scenario_contexts', 'scope_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('risk_scenario_contexts', 'scope_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_scenario_contexts', 'scope_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('risk_scenario_contexts', 'scope_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'site_id')
    op.drop_column('assets', 'business_unit_id')
    op.drop_column('assets', 'entity_id')
    # ### end Alembic commands ###
