"""asset_type to vuln 

Revision ID: 72e80bbbdf2a
Revises: 5a48b674e6cb
Create Date: 2025-08-08 18:59:07.622732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e80bbbdf2a'
down_revision: Union[str, Sequence[str], None] = '5a48b674e6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type_vulnerability_links', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('asset_type_vulnerability_links', sa.Column('justification', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_type_vulnerability_links', 'justification')
    op.drop_column('asset_type_vulnerability_links', 'score')
    # ### end Alembic commands ###
