"""risk scenario context-refactor 3

Revision ID: 827d7559d11c
Revises: 4e31a05c6fd1
Create Date: 2025-08-05 14:12:56.175853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827d7559d11c'
down_revision: Union[str, Sequence[str], None] = '4e31a05c6fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
