"""scope migration 1

Revision ID: 84fb1d52b75c
Revises: f9561715f13e
Create Date: 2025-08-16 12:01:31.272899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fb1d52b75c'
down_revision: Union[str, Sequence[str], None] = 'f9561715f13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_context_links', sa.Column('scope_type', sa.String(length=30), nullable=True))
    op.add_column('control_context_links', sa.Column('scope_id', sa.Integer(), nullable=True))
    op.alter_column('control_context_links', 'risk_scenario_context_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('uq_ctrl_scope', 'control_context_links', ['scope_type', 'scope_id', 'control_id'], unique=True, postgresql_where=sa.text('risk_scenario_context_id IS NULL'))
    op.add_column('risk_scenario_contexts', sa.Column('scope_type', sa.String(length=30), nullable=False))
    op.add_column('risk_scenario_contexts', sa.Column('scope_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_rsc_asset'), 'risk_scenario_contexts', type_='unique')
    op.drop_constraint(op.f('uq_rsc_group'), 'risk_scenario_contexts', type_='unique')
    op.drop_constraint(op.f('uq_rsc_tag'), 'risk_scenario_contexts', type_='unique')
    op.drop_constraint(op.f('uq_rsc_type'), 'risk_scenario_contexts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_rsc_type'), 'risk_scenario_contexts', ['risk_scenario_id', 'asset_type_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_rsc_tag'), 'risk_scenario_contexts', ['risk_scenario_id', 'asset_tag_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_rsc_group'), 'risk_scenario_contexts', ['risk_scenario_id', 'asset_group_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_rsc_asset'), 'risk_scenario_contexts', ['risk_scenario_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('risk_scenario_contexts', 'scope_id')
    op.drop_column('risk_scenario_contexts', 'scope_type')
    op.drop_index('uq_ctrl_scope', table_name='control_context_links', postgresql_where=sa.text('risk_scenario_context_id IS NULL'))
    op.alter_column('control_context_links', 'risk_scenario_context_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('control_context_links', 'scope_id')
    op.drop_column('control_context_links', 'scope_type')
    # ### end Alembic commands ###
