"""add owner to context

Revision ID: 8a42653d0925
Revises: 688f577bc07a
Create Date: 2025-08-26 10:55:26.082681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a42653d0925'
down_revision: Union[str, Sequence[str], None] = '688f577bc07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenario_contexts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_risk_scenario_contexts_owner_id'), 'risk_scenario_contexts', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'risk_scenario_contexts', 'persons', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_scenario_contexts', type_='foreignkey')
    op.drop_index(op.f('ix_risk_scenario_contexts_owner_id'), table_name='risk_scenario_contexts')
    op.drop_column('risk_scenario_contexts', 'owner_id')
    # ### end Alembic commands ###
