"""add policy contorls

Revision ID: 8c62d8f55207
Revises: 5f2a41cfbe34
Create Date: 2025-08-13 15:16:20.636833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c62d8f55207'
down_revision: Union[str, Sequence[str], None] = '5f2a41cfbe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_applicability_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=16), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag_id', sa.Integer(), nullable=True),
    sa.Column('asset_group_id', sa.Integer(), nullable=True),
    sa.Column('controls_json', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ),
    sa.ForeignKeyConstraint(['asset_tag_id'], ['asset_tags.id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_applicability_policies')
    # ### end Alembic commands ###
