"""add soa

Revision ID: 8e1ecece4cd0
Revises: b18abd5eaba2
Create Date: 2025-09-02 22:08:33.809972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1ecece4cd0'
down_revision: Union[str, Sequence[str], None] = 'b18abd5eaba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_context_links', sa.Column('applicability', sa.String(length=16), nullable=True))
    op.add_column('control_context_links', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('control_context_links', sa.Column('approver', sa.String(length=120), nullable=True))
    op.add_column('control_context_links', sa.Column('decided_at', sa.Date(), nullable=True))
    op.add_column('control_context_links', sa.Column('expires_at', sa.Date(), nullable=True))
    op.add_column('control_context_links', sa.Column('owner', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_context_links', 'owner')
    op.drop_column('control_context_links', 'expires_at')
    op.drop_column('control_context_links', 'decided_at')
    op.drop_column('control_context_links', 'approver')
    op.drop_column('control_context_links', 'justification')
    op.drop_column('control_context_links', 'applicability')
    # ### end Alembic commands ###
