"""add contraints to risk_scenario_contexts

Revision ID: 90ef1584cc81
Revises: feb7882e0399
Create Date: 2025-08-10 15:23:52.470811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ef1584cc81'
down_revision: Union[str, Sequence[str], None] = 'feb7882e0399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenario_contexts', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_rsc_asset', 'risk_scenario_contexts', ['risk_scenario_id', 'asset_id'])
    op.create_unique_constraint('uq_rsc_group', 'risk_scenario_contexts', ['risk_scenario_id', 'asset_group_id'])
    op.create_unique_constraint('uq_rsc_tag', 'risk_scenario_contexts', ['risk_scenario_id', 'asset_tag_id'])
    op.create_unique_constraint('uq_rsc_type', 'risk_scenario_contexts', ['risk_scenario_id', 'asset_type_id'])
    op.create_foreign_key(None, 'risk_scenario_contexts', 'asset_types', ['asset_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_scenario_contexts', type_='foreignkey')
    op.drop_constraint('uq_rsc_type', 'risk_scenario_contexts', type_='unique')
    op.drop_constraint('uq_rsc_tag', 'risk_scenario_contexts', type_='unique')
    op.drop_constraint('uq_rsc_group', 'risk_scenario_contexts', type_='unique')
    op.drop_constraint('uq_rsc_asset', 'risk_scenario_contexts', type_='unique')
    op.drop_column('risk_scenario_contexts', 'asset_type_id')
    # ### end Alembic commands ###
