"""add evidence lifecycle

Revision ID: 91e183c42761
Revises: a92ed77ae249
Create Date: 2025-08-28 22:10:59.248828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e183c42761'
down_revision: Union[str, Sequence[str], None] = 'a92ed77ae249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_evidence', sa.Column('lifecycle_status', sa.String(length=20), nullable=False))
    op.add_column('control_evidence', sa.Column('supersedes_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'control_evidence', 'control_evidence', ['supersedes_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_evidence', type_='foreignkey')
    op.drop_column('control_evidence', 'supersedes_id')
    op.drop_column('control_evidence', 'lifecycle_status')
    # ### end Alembic commands ###
