"""add framework version

Revision ID: 9b813b7e2286
Revises: a833b03ddcce
Create Date: 2025-08-14 10:30:34.944900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b813b7e2286'
down_revision: Union[str, Sequence[str], None] = 'a833b03ddcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('framework_requirements', sa.Column('framework_version_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_fwr_fw_parent_sort'), table_name='framework_requirements')
    op.create_index('ix_fwr_v_parent_sort', 'framework_requirements', ['framework_version_id', 'parent_id', 'sort_index'], unique=False)
    op.drop_constraint(op.f('framework_requirements_framework_id_fkey'), 'framework_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'framework_requirements', 'framework_versions', ['framework_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('framework_requirements', 'framework_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_requirements', sa.Column('framework_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'framework_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('framework_requirements_framework_id_fkey'), 'framework_requirements', 'frameworks', ['framework_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_fwr_v_parent_sort', table_name='framework_requirements')
    op.create_index(op.f('ix_fwr_fw_parent_sort'), 'framework_requirements', ['framework_id', 'parent_id', 'sort_index'], unique=False)
    op.drop_column('framework_requirements', 'framework_version_id')
    op.drop_table('framework_versions')
    # ### end Alembic commands ###
