"""add control effect rating

Revision ID: 9eb203a319f2
Revises: 6bc555158161
Create Date: 2025-08-02 16:27:57.980876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb203a319f2'
down_revision: Union[str, Sequence[str], None] = '6bc555158161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_effect_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_scenario_id', sa.Integer(), nullable=True),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['impact_domains.id'], ),
    sa.ForeignKeyConstraint(['risk_scenario_id'], ['risk_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_effect_rating')
    # ### end Alembic commands ###
