"""asset_type control link

Revision ID: a708e3f4358e
Revises: 72e80bbbdf2a
Create Date: 2025-08-09 16:07:37.858187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a708e3f4358e'
down_revision: Union[str, Sequence[str], None] = '72e80bbbdf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type_control_links', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('asset_type_control_links', sa.Column('justification', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_type_control_links', 'justification')
    op.drop_column('asset_type_control_links', 'score')
    # ### end Alembic commands ###
