"""refactor framework

Revision ID: a833b03ddcce
Revises: df8f3bcd55ea
Create Date: 2025-08-14 09:26:47.232385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a833b03ddcce'
down_revision: Union[str, Sequence[str], None] = 'df8f3bcd55ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_requirements', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('framework_requirements', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('framework_requirements', sa.Column('sort_index', sa.Integer(), nullable=False))
    op.alter_column('framework_requirements', 'code',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('framework_requirements', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.drop_constraint(op.f('uq_fw_req_code'), 'framework_requirements', type_='unique')
    op.create_index('ix_fwr_fw_parent_sort', 'framework_requirements', ['framework_id', 'parent_id', 'sort_index'], unique=False)
    op.create_foreign_key(None, 'framework_requirements', 'framework_requirements', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('framework_requirements', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_requirements', sa.Column('notes', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'framework_requirements', type_='foreignkey')
    op.drop_index('ix_fwr_fw_parent_sort', table_name='framework_requirements')
    op.create_unique_constraint(op.f('uq_fw_req_code'), 'framework_requirements', ['framework_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('framework_requirements', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('framework_requirements', 'code',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('framework_requirements', 'sort_index')
    op.drop_column('framework_requirements', 'parent_id')
    op.drop_column('framework_requirements', 'text')
    # ### end Alembic commands ###
