"""add next_review to risk_scenario_contexts

Revision ID: a92ed77ae249
Revises: 247a1dfcc239
Create Date: 2025-08-27 23:59:55.721705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92ed77ae249'
down_revision: Union[str, Sequence[str], None] = '247a1dfcc239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenario_contexts', sa.Column('next_review', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scenario_contexts', 'next_review')
    # ### end Alembic commands ###
