"""risk add risk scores2

Revision ID: aabc9b1f8ff1
Revises: a7106b4c40a1
Create Date: 2025-08-06 15:47:51.130751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabc9b1f8ff1'
down_revision: Union[str, Sequence[str], None] = 'a7106b4c40a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_score_history',
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=True),
    sa.Column('initial_score', sa.Float(), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('initial_by_domain', sa.JSON(), nullable=True),
    sa.Column('residual_by_domain', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_score_history_risk_scenario_context_id'), 'risk_score_history', ['risk_scenario_context_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=True),
    sa.Column('initial_score', sa.Float(), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('initial_by_domain', sa.JSON(), nullable=True),
    sa.Column('residual_by_domain', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_risk_scenario_context_id'), 'risk_scores', ['risk_scenario_context_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_risk_scenario_context_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_risk_score_history_risk_scenario_context_id'), table_name='risk_score_history')
    op.drop_table('risk_score_history')
    # ### end Alembic commands ###
