"""control_context add updated_at to contexts

Revision ID: b022ff81d03b
Revises: 5432d828ba71
Create Date: 2025-08-11 14:26:44.142010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b022ff81d03b'
down_revision: Union[str, Sequence[str], None] = '5432d828ba71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenario_contexts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('risk_scenario_contexts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('risk_scenario_contexts', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scenario_contexts', 'enabled')
    op.drop_column('risk_scenario_contexts', 'updated_at')
    op.drop_column('risk_scenario_contexts', 'created_at')
    # ### end Alembic commands ###
