"""add status to risk_scenarios

Revision ID: b1895b0bf4c3
Revises: c6c7594a6cb4
Create Date: 2025-08-01 16:18:22.069146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1895b0bf4c3'
down_revision: Union[str, Sequence[str], None] = 'c6c7594a6cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scenarios', 'status')
    # ### end Alembic commands ###
