"""update exception

Revision ID: b18abd5eaba2
Revises: 136674945f1f
Create Date: 2025-09-02 15:20:52.676681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18abd5eaba2'
down_revision: Union[str, Sequence[str], None] = '136674945f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_exceptions', 'risk_scenario_context_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('compliance_exceptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_exceptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('compliance_exceptions', 'risk_scenario_context_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
