"""evidence models2

Revision ID: b894fa6eeec5
Revises: 7b0bbb5392da
Create Date: 2025-08-23 17:22:22.622291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b894fa6eeec5'
down_revision: Union[str, Sequence[str], None] = '7b0bbb5392da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_context_link_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('submitted','accepted','rejected','expired')", name='evi_status_valid'),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_context_link_id'], ['control_context_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evi_expires', 'evidence_items', ['expires_at'], unique=False)
    op.create_index('idx_evi_link_status', 'evidence_items', ['control_context_link_id', 'status'], unique=False)
    op.create_index(op.f('ix_evidence_items_artifact_id'), 'evidence_items', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_control_context_link_id'), 'evidence_items', ['control_context_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_control_context_link_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_artifact_id'), table_name='evidence_items')
    op.drop_index('idx_evi_link_status', table_name='evidence_items')
    op.drop_index('idx_evi_expires', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_table('evidence_artifacts')
    # ### end Alembic commands ###
