"""risk scenario likelihood/impact

Revision ID: be5627dd0381
Revises: 17a1d4137166
Create Date: 2025-08-23 13:03:42.730369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be5627dd0381'
down_revision: Union[str, Sequence[str], None] = '17a1d4137166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scenarios', sa.Column('likelihood', sa.Integer(), nullable=True))
    op.add_column('risk_scenarios', sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scenarios', 'impact')
    op.drop_column('risk_scenarios', 'likelihood')
    # ### end Alembic commands ###
