"""Add Person table

Revision ID: cabb05d1b48f
Revises: 6a9d9bc9e7e3
Create Date: 2025-07-20 20:14:58.501682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabb05d1b48f'
down_revision: Union[str, Sequence[str], None] = '6a9d9bc9e7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
                    schema='secura'
    )
    # op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_security_profiles', schema='secura')
    op.drop_table('asset_scans', schema='secura')
    op.drop_table('asset_relations', schema='secura')
    op.drop_table('asset_owners', schema='secura')
    op.drop_table('asset_maintenance', schema='secura')
    op.drop_table('asset_lifecycle_events', schema='secura')
    op.drop_table('assets', schema='secura')
    op.drop_table('asset_types', schema='secura')
    op.drop_table('asset_groups', schema='secura')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
