"""add username

Revision ID: cc7315a5f79c
Revises: 9343b2f82f1a
Create Date: 2025-09-03 09:05:45.333837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7315a5f79c'
down_revision: Union[str, Sequence[str], None] = '9343b2f82f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iam_users', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.drop_index(op.f('ix_iam_users_email'), table_name='iam_users')
    op.create_index('ix_iam_users_email', 'iam_users', ['email'], unique=False)
    op.create_index(op.f('ix_iam_users_user_name'), 'iam_users', ['user_name'], unique=True)
    op.create_index('ix_iam_users_username', 'iam_users', ['user_name'], unique=False)
    op.create_unique_constraint('uq_user_username', 'iam_users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'iam_users', type_='unique')
    op.drop_index('ix_iam_users_username', table_name='iam_users')
    op.drop_index(op.f('ix_iam_users_user_name'), table_name='iam_users')
    op.drop_index('ix_iam_users_email', table_name='iam_users')
    op.create_index(op.f('ix_iam_users_email'), 'iam_users', ['email'], unique=True)
    op.drop_column('iam_users', 'user_name')
    # ### end Alembic commands ###
