"""evidence integrate2

Revision ID: d02775ec4f55
Revises: 36474fc22712
Create Date: 2025-09-01 11:16:49.464958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02775ec4f55'
down_revision: Union[str, Sequence[str], None] = '36474fc22712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_control_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_context_link_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v_control_evidence')
    # ### end Alembic commands ###
