"""add exception

Revision ID: d5bfe846097c
Revises: 923b85add30a
Create Date: 2025-08-14 15:58:42.658547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bfe846097c'
down_revision: Union[str, Sequence[str], None] = '923b85add30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_scenario_context_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('framework_requirement_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_acceptance_ref', sa.String(length=500), nullable=True),
    sa.Column('compensating_controls', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_requirement_id'], ['framework_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_scenario_context_id'], ['risk_scenario_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exc_context', 'compliance_exceptions', ['risk_scenario_context_id'], unique=False)
    op.create_index('ix_exc_status', 'compliance_exceptions', ['status'], unique=False)
    op.create_index('ix_exc_target_ctrl', 'compliance_exceptions', ['control_id'], unique=False)
    op.create_index('ix_exc_target_req', 'compliance_exceptions', ['framework_requirement_id'], unique=False)
    op.create_table('compliance_exception_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['compliance_exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_exception_comments')
    op.drop_index('ix_exc_target_req', table_name='compliance_exceptions')
    op.drop_index('ix_exc_target_ctrl', table_name='compliance_exceptions')
    op.drop_index('ix_exc_status', table_name='compliance_exceptions')
    op.drop_index('ix_exc_context', table_name='compliance_exceptions')
    op.drop_table('compliance_exceptions')
    # ### end Alembic commands ###
