"""add asset groups

Revision ID: d6ffb1675473
Revises: 1430c4fc1679
Create Date: 2025-07-17 17:34:50.476058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ffb1675473'
down_revision: Union[str, Sequence[str], None] = '1430c4fc1679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['secura.asset_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    op.add_column('assets',
                  sa.Column('group_id', sa.Integer(), nullable=True),
                  schema='secura'
                  )

    op.create_foreign_key(
        'fk_assets_group_id',
        'assets', 'asset_groups',
        ['group_id'], ['id'],
        source_schema='secura',
        referent_schema='secura'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secura_assets_id'), table_name='assets', schema='secura')
    op.drop_table('assets', schema='secura')
    op.drop_table('asset_groups', schema='secura')
    # ### end Alembic commands ###
