"""vulner & link to threats add

Revision ID: dfb5cd72fccf
Revises: a93e15a91b84
Create Date: 2025-07-23 17:57:07.369956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb5cd72fccf'
down_revision: Union[str, Sequence[str], None] = 'a93e15a91b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='secura'
    )
    op.create_table('vulnerability_threat_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['threat_id'], ['secura.threats.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['secura.vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secura'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability_threat_links', schema='secura')
    op.drop_table('vulnerabilities', schema='secura')
    # ### end Alembic commands ###
