"""update controls with source

Revision ID: eaccd1ba8bcc
Revises: 245576892309
Create Date: 2025-07-29 18:15:46.647240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaccd1ba8bcc'
down_revision: Union[str, Sequence[str], None] = '245576892309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('control_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'control_source')
    # ### end Alembic commands ###
