"""add status and .. to control-risk by control

Revision ID: f40c0cba9ebd
Revises: 6765ce3762de
Create Date: 2025-08-01 19:30:11.006747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40c0cba9ebd'
down_revision: Union[str, Sequence[str], None] = '6765ce3762de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
