"""update risk_scenario fix tag

Revision ID: f9e9f4177e1b
Revises: 4ae9d59b4621
Create Date: 2025-07-31 13:36:34.658405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e9f4177e1b'
down_revision: Union[str, Sequence[str], None] = '4ae9d59b4621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
