"""remove version from frameworks

Revision ID: f9feb48be701
Revises: 27b8a7683a1e
Create Date: 2025-08-15 19:44:47.073292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9feb48be701'
down_revision: Union[str, Sequence[str], None] = '27b8a7683a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frameworks', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frameworks', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
