export const sampleTasks = [
  {
    id: 't-1001',
    type: 'attestation',
    title: 'Q3 Access Review — Engineering',
    objectType: 'Control',
    objectCode: 'AC-02',
    scope: 'prod',
    versions: 'current',
    assignee: 'you@company.com',
    dueDate: '2025-09-15',
    status: 'in_progress',
    priority: 'high',
    link: '/controls?code=AC-02',
    details: 'Attest that user access is reviewed and certified.',
  },
  {
    id: 't-1002',
    type: 'evidence',
    title: 'Upload firewall change log (Aug)',
    objectType: 'Requirement',
    objectCode: 'A.8.8',
    scope: 'prod',
    versions: 'current',
    assignee: 'secops@company.com',
    dueDate: '2025-09-05',
    status: 'overdue',
    priority: 'medium',
    link: '/evidence',
    details: 'Provide monthly change logs from Panorama.',
  },
  {
    id: 't-1003',
    type: 'exception',
    title: 'S3 public-read for data share (temporary)',
    objectType: 'Control',
    objectCode: 'SC-13',
    scope: 'global',
    versions: 'current',
    assignee: 'risk@company.com',
    dueDate: '2025-09-30',
    status: 'new',
    priority: 'low',
    link: '/risks',
    details: 'Exception request pending review by committee.',
  },
  {
    id: 't-1004',
    type: 'mapping',
    title: 'Map SOC2 CC5.2 to AC-02',
    objectType: 'Requirement',
    objectCode: 'CC5.2',
    scope: 'prod',
    versions: 'v2',
    assignee: 'analyst@company.com',
    dueDate: '2025-09-20',
    status: 'blocked',
    priority: 'high',
    link: '/compliance',
    details: 'Need confirming control test evidence to complete mapping.',
  },
  {
    id: 't-1005',
    type: 'treatment',
    title: 'Implement SSO for contractor accounts',
    objectType: 'Risk',
    objectCode: 'R-124',
    scope: 'prod',
    versions: 'current',
    assignee: 'it-iam@company.com',
    dueDate: '2025-10-10',
    status: 'new',
    priority: 'high',
    link: '/risks',
    details: 'Mitigation plan approved; awaiting rollout.',
  },

  // --- Extra rows so /my-work works even with ?scope=a&versions=v1 ---
  {
    id: 't-2001',
    type: 'evidence',
    title: 'Upload change tickets (Sept)',
    objectType: 'Requirement',
    objectCode: 'A.12.1',
    scope: 'a',
    versions: 'v1',
    assignee: 'ops@company.com',
    dueDate: '2025-09-18',
    status: 'new',
    priority: 'medium',
    link: '/compliance',
    details: 'Monthly operational change tickets.',
  },
  {
    id: 't-2002',
    type: 'attestation',
    title: 'Quarterly admin review — Finance',
    objectType: 'Control',
    objectCode: 'AC-06',
    scope: 'a',
    versions: 'v1',
    assignee: 'finance@company.com',
    dueDate: '2025-09-28',
    status: 'in_progress',
    priority: 'high',
    link: '/controls?code=AC-06',
    details: 'Confirm least privilege for finance admins.',
  },
];
